[versions]
agp = "8.3.0"
hilt = "2.51"
kotlin = "1.9.23"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
ksp = "1.9.23-1.0.19"
ktlint = "12.1.0"
navigation = "2.7.7"
rxJava = "3.1.8"
rxAndroid = "3.0.2"
gson = "2.10.1"
okhttp = "5.0.0-alpha.12"
apollo = "4.0.0-beta.5"
dataStore = "1.0.0"
viewPager2 = "1.0.0"
room = "2.6.1"
calendar = "2.5.0"
firebase = "32.7.4"
kakaoMap = "2.9.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
navigation-dynamic-features-fragment = { group = "androidx.navigation", name = "navigation-dynamic-features-fragment", version.ref = "navigation" }
rxJava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxJava" }
rxAndroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxAndroid" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
apollo = { group = "com.apollographql.apollo3", name = "apollo-runtime", version.ref = "apollo" }
dataStore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
dataStoreRx = { group = "androidx.datastore", name = "datastore-preferences-rxjava3", version.ref = "dataStore" }
viewPager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewPager2" }
room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
roomRx = { group = "androidx.room", name = "room-rxjava3", version.ref = "room" }
roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
roomPaging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
calendar = { group = "com.kizitonwose.calendar", name = "view", version.ref = "calendar" }
firebase = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebaseAnalytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebaseCrashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebaseMessaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
kakaoMap = { group = "com.kakao.maps.open", name = "android", version.ref = "kakaoMap" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hiltPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }

