name: Android App Build
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    name: Android App Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get sign key
        run: |
          echo $BASE64_KEYSTORE | base64 --decode > app/release-key.jks          
          echo $BASE64_KEYSTORE | base64 --decode > watch/release-key.jks
        env:
          BASE64_KEYSTORE: ${{ secrets.BASE64_KEYSTORE }}

      - name: Create local.properties
        run: |
          echo "SIGNED_KEY_ALIAS=$SIGNED_KEY_ALIAS" > local.properties
          echo "SIGNED_KEY_PASSWORD=$SIGNED_KEY_PASSWORD" >> local.properties
          echo "SIGNED_STORE_PASSWORD=$SIGNED_STORE_PASSWORD" >> local.properties
          echo "SIGNING_KEY_FILE=./release-key.jks" >> local.properties
          echo "MAP_API_KEY=\"$MAP_KEY\"" >> local.properties
          echo "API_URL=\"$RELEASE_API_URL\"" >> local.properties
        env:
          SIGNED_KEY_ALIAS: ${{ secrets.SIGNED_KEY_ALIAS }}
          SIGNED_KEY_PASSWORD: ${{ secrets.SIGNED_KEY_PASSWORD }}
          SIGNED_STORE_PASSWORD: ${{ secrets.SIGNED_STORE_PASSWORD }}
          MAP_KEY: ${{ secrets.MAP_KEY }}
          API_URL: ${{ secrets.API_URL }}
      - name: Create google-services.json
        run: echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - name: Build Release App Bundle
        run: ./gradlew bundleRelease
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/bundle/release/app-release.aab
          retention-days: 3
